import type { ServiceConfig } from '@/services/service-config'
import { COLOR_SCHEME_OPTIONS } from '@/config/color-schemes'

export const couvertureConfig: ServiceConfig = {
  id: 'couverture',
  title: 'Couverture',
  dataFile: `${import.meta.env.BASE_URL}data/couverture.csv`,
  formControls: [
    {
      key: 'metric',
      label: 'Indicateur',
      entries: [
        { label: '% de la population couverte', key: 'pct_pop' },
        { label: '% des communes équipées', key: 'pct_communes' },
      ],
    },
    {
      key: 'facility',
      label: 'Service ou équipement',
      entries: [
        { label: 'Aéroport', key: 'aeroport' },
        { label: 'Agence postale', key: 'agence_postale' },
        { label: 'Ambulance', key: 'ambulance' },
        { label: 'Arts du spectacle', key: 'arts_du_spectacle' },
        { label: 'Bibliothèque', key: 'bibliotheque' },
        { label: 'Bureau de poste', key: 'bureau_de_poste' },
        { label: 'Chirurgien-dentiste', key: 'chirurgien_dentiste' },
        { label: 'Cinéma', key: 'cinema' },
        { label: 'Collège', key: 'college' },
        { label: 'Déchèterie', key: 'decheterie' },
        { label: 'Dialyse', key: 'dialyse' },
        { label: 'École élémentaire', key: 'ecole_elementaire' },
        { label: 'École maternelle', key: 'ecole_maternelle' },
        { label: 'École primaire', key: 'ecole_primaire' },
        { label: 'Établissement de santé (court séjour)', key: 'etablissement_sante_court_sejour' },
        { label: 'Établissement de santé (long séjour)', key: 'etablissement_sante_long_sejour' },
        { label: 'Établissement de santé (moyen séjour)', key: 'etablissement_sante_moyen_sejour' },
        { label: 'Gare de voyageurs d\'intérêt local', key: 'gare_de_voyageurs_d_interet_local' },
        { label: 'Gare de voyageurs d\'intérêt national', key: 'gare_de_voyageurs_d_interet_national' },
        { label: 'Gare de voyageurs d\'intérêt régional', key: 'gare_de_voyageurs_d_interet_regional' },
        { label: 'Gendarmerie', key: 'gendarmerie' },
        { label: 'Implantation France Services (IFS)', key: 'implantations_france_services_ifs' },
        { label: 'Infirmier·ère', key: 'infirmier' },
        { label: 'Laboratoire d\'analyses et de biologie médicale', key: 'laboratoire_d_analyses_et_de_biologie_medicale' },
        { label: 'Lycée d\'enseignement général et/ou technologique', key: 'lycee_d_enseignement_general_et_ou_technologique' },
        { label: 'Lycée d\'enseignement professionnel', key: 'lycee_d_enseignement_professionnel' },
        { label: 'Lycée d\'enseignement technique et/ou professionnel agricole', key: 'lycee_d_enseignement_technique_et_ou_professionnel_agricole' },
        { label: 'Maternité', key: 'maternite' },
        { label: 'Médecin généraliste', key: 'medecin_generaliste' },
        { label: 'Pharmacie', key: 'pharmacie' },
        { label: 'Police', key: 'police' },
        { label: 'Réseau de proximité Pôle emploi', key: 'reseau_de_proximite_pole_emploi' },
        { label: 'Sage-femme', key: 'sage_femme' },
        { label: 'Urgences', key: 'urgences' },
      ],
    },
    {
      key: 'colorScheme',
      label: 'Palette de couleurs',
      entries: COLOR_SCHEME_OPTIONS,
    },
  ],
  rendering: {
    titleTemplates: {
      pct_communes: {
        default: 'Part des communes disposant d\'au moins un équipement ou service "{facility}"',
        aeroport: 'Part des communes desservies par un aéroport',
        agence_postale: 'Part des communes disposant d\'une agence postale',
        ambulance: 'Part des communes disposant d\'un service d\'ambulance',
        arts_du_spectacle: 'Part des communes disposant d\'une salle de spectacle',
        bibliotheque: 'Part des communes équipées d\'une bibliothèque',
        bureau_de_poste: 'Part des communes disposant d\'un bureau de poste',
        chirurgien_dentiste: 'Part des communes disposant d\'au moins un chirurgien-dentiste',
        cinema: 'Part des communes équipées d\'un cinéma',
        college: 'Part des communes disposant d\'un collège',
        decheterie: 'Part des communes équipées d\'une déchèterie',
        dialyse: 'Part des communes disposant d\'un centre de dialyse',
        ecole_elementaire: 'Part des communes disposant d\'une école élémentaire',
        ecole_maternelle: 'Part des communes disposant d\'une école maternelle',
        ecole_primaire: 'Part des communes disposant d\'une école primaire',
        etablissement_sante_court_sejour: 'Part des communes disposant d\'un établissement de santé (court séjour)',
        etablissement_sante_long_sejour: 'Part des communes disposant d\'un établissement de santé (long séjour)',
        etablissement_sante_moyen_sejour: 'Part des communes disposant d\'un établissement de santé (moyen séjour)',
        gare_de_voyageurs_d_interet_local: 'Part des communes desservies par une gare d\'intérêt local',
        gare_de_voyageurs_d_interet_national: 'Part des communes desservies par une gare d\'intérêt national',
        gare_de_voyageurs_d_interet_regional: 'Part des communes desservies par une gare d\'intérêt régional',
        gendarmerie: 'Part des communes disposant d\'une brigade de gendarmerie',
        implantations_france_services_ifs: 'Part des communes disposant d\'une maison France Services',
        infirmier: 'Part des communes disposant d\'au moins un·e infirmier·ère',
        laboratoire_d_analyses_et_de_biologie_medicale: 'Part des communes disposant d\'un laboratoire d\'analyses médicales',
        lycee_d_enseignement_general_et_ou_technologique: 'Part des communes disposant d\'un lycée général et/ou technologique',
        lycee_d_enseignement_professionnel: 'Part des communes disposant d\'un lycée professionnel',
        lycee_d_enseignement_technique_et_ou_professionnel_agricole: 'Part des communes disposant d\'un lycée agricole',
        maternite: 'Part des communes disposant d\'une maternité',
        medecin_generaliste: 'Part des communes disposant d\'au moins un médecin généraliste',
        pharmacie: 'Part des communes équipées d\'une pharmacie',
        police: 'Part des communes disposant d\'un commissariat de police',
        reseau_de_proximite_pole_emploi: 'Part des communes desservies par une agence Pôle emploi',
        sage_femme: 'Part des communes disposant d\'au moins une sage-femme',
        urgences: 'Part des communes disposant d\'un service d\'urgences',
      },
      pct_pop: {
        default: 'Part de la population couverte par un équipement ou service : "{facility}"',
        aeroport: 'Part de la population desservie par un aéroport',
        agence_postale: 'Part de la population ayant accès à une agence postale',
        ambulance: 'Part de la population couverte par un service d\'ambulance',
        arts_du_spectacle: 'Part de la population ayant accès à une salle de spectacle',
        bibliotheque: 'Part de la population ayant accès à une bibliothèque',
        bureau_de_poste: 'Part de la population ayant accès à un bureau de poste',
        chirurgien_dentiste: 'Part de la population ayant accès à un chirurgien-dentiste',
        cinema: 'Part de la population ayant accès à un cinéma',
        college: 'Part de la population ayant accès à un collège',
        decheterie: 'Part de la population ayant accès à une déchèterie',
        dialyse: 'Part de la population ayant accès à un centre de dialyse',
        ecole_elementaire: 'Part de la population ayant accès à une école élémentaire',
        ecole_maternelle: 'Part de la population ayant accès à une école maternelle',
        ecole_primaire: 'Part de la population ayant accès à une école primaire',
        etablissement_sante_court_sejour: 'Part de la population couverte par un établissement de santé (court séjour)',
        etablissement_sante_long_sejour: 'Part de la population couverte par un établissement de santé (long séjour)',
        etablissement_sante_moyen_sejour: 'Part de la population couverte par un établissement de santé (moyen séjour)',
        gare_de_voyageurs_d_interet_local: 'Part de la population desservie par une gare d\'intérêt local',
        gare_de_voyageurs_d_interet_national: 'Part de la population desservie par une gare d\'intérêt national',
        gare_de_voyageurs_d_interet_regional: 'Part de la population desservie par une gare d\'intérêt régional',
        gendarmerie: 'Part de la population couverte par une brigade de gendarmerie',
        implantations_france_services_ifs: 'Part de la population ayant accès à une maison France Services',
        infirmier: 'Part de la population ayant accès à un·e infirmier·ère',
        laboratoire_d_analyses_et_de_biologie_medicale: 'Part de la population ayant accès à un laboratoire d\'analyses médicales',
        lycee_d_enseignement_general_et_ou_technologique: 'Part de la population ayant accès à un lycée général et/ou technologique',
        lycee_d_enseignement_professionnel: 'Part de la population ayant accès à un lycée professionnel',
        lycee_d_enseignement_technique_et_ou_professionnel_agricole: 'Part de la population ayant accès à un lycée agricole',
        maternite: 'Part de la population couverte par une maternité',
        medecin_generaliste: 'Part de la population ayant accès à un médecin généraliste',
        pharmacie: 'Part de la population ayant accès à une pharmacie',
        police: 'Part de la population couverte par un commissariat de police',
        reseau_de_proximite_pole_emploi: 'Part de la population desservie par une agence Pôle emploi',
        sage_femme: 'Part de la population ayant accès à une sage-femme',
        urgences: 'Part de la population couverte par un service d\'urgences',
      },
    },
    colorSchemes: {
      pct_pop: {
        scheme: 'blues',
        label: '% population',
        percent: true,
      },
      pct_communes: {
        scheme: 'purples',
        label: '% communes',
        percent: true,
      },
    },
    dataKeys: {
      rowKey: 'DEP',
      featureKey: 'default',
    },
    tooltip: {
      template: 'dual-metric',
      includeSecondaryMetric: true,
    },
  },
}
