import type { ServiceConfig } from '@/services/service-config'
import { COLOR_SCHEME_OPTIONS } from '@/config/color-schemes'

export const eloignementConfig: ServiceConfig = {
  id: 'eloignement',
  title: 'Éloignements',
  dataFile: `${import.meta.env.BASE_URL}data/eloignement.csv`,

  // Preprocessor to expand aggregate DOM code "97" to individual DOM territories
  dataPreprocessor: (rows) => {
    const DOM_CODES = ['971', '972', '973', '974', '976']
    const expandedRows: any[] = []

    for (const row of rows) {
      if (row.dep === '97') {
        // Replicate this row for each DOM territory
        for (const code of DOM_CODES) {
          expandedRows.push({ ...row, dep: code })
        }
      }
      else {
        expandedRows.push(row)
      }
    }

    return expandedRows
  },

  formControls: [
    {
      key: 'metric',
      label: 'Temps d\'accès',
      entries: [
        { label: '5 minutes', key: '5min' },
        { label: '10 minutes', key: '10min' },
        { label: '15 minutes', key: '15min' },
        { label: '20 minutes', key: '20min' },
        { label: '30 minutes', key: '30min' },
        { label: '45 minutes', key: '45min' },
        { label: '60 minutes', key: '60min' },
      ],
    },
    {
      key: 'facility',
      label: 'Service ou équipement',
      entries: [
        { label: 'Police', key: 'police' },
        { label: 'Gendarmerie', key: 'gendarmerie' },
        { label: 'Réseau de proximité Pôle emploi', key: 'reseau_de_proximite_pole_emploi' },
        { label: 'Aéroport', key: 'aeroport' },
        { label: 'Gare de voyageurs d’intérêt national', key: 'gare_de_voyageurs_d_interet_nat' },
        { label: 'Gare de voyageurs d’intérêt régional', key: 'gare_de_voyageurs_d_interet_reg' },
        { label: 'Gare de voyageurs d’intérêt local', key: 'gare_de_voyageurs_d_interet_loc' },
        { label: 'Implantations France Services (IFS)', key: 'implantations_france_services_i' },
        { label: 'Bureau de poste', key: 'bureau_de_poste' },
        { label: 'Agence postale', key: 'agence_postale' },
        { label: 'École maternelle', key: 'ecole_maternelle' },
        { label: 'École primaire', key: 'ecole_primaire' },
        { label: 'École élémentaire', key: 'ecole_elementaire' },
        { label: 'Collège', key: 'college' },
        { label: 'Lycée d’enseignement général et/ou technologique', key: 'lycee_d_enseignement_general_et' },
        { label: 'Lycée d’enseignement professionnel', key: 'lycee_d_enseignement_profession' },
        { label: 'Lycée d’enseignement technique et/ou professionnel agricole', key: 'lycee_d_enseignement_technique_' },
        { label: 'Établissement de santé (court séjour)', key: 'etablissement_sante_court_sejou' },
        { label: 'Établissement de santé (moyen séjour)', key: 'etablissement_sante_moyen_sejou' },
        { label: 'Établissement de santé (long séjour)', key: 'etablissement_sante_long_sejour' },
        { label: 'Chirurgien-dentiste', key: 'chirurgien_dentiste' },
        { label: 'Infirmier·ère', key: 'infirmier' },
        { label: 'Laboratoire d’analyses et de biologie médicale', key: 'laboratoire_d_analyses_et_de_bi' },
        { label: 'Ambulance', key: 'ambulance' },
        { label: 'Pharmacie', key: 'pharmacie' },
        { label: 'Cinéma', key: 'cinema' },
        { label: 'Bibliothèque', key: 'bibliotheque' },
        { label: 'Arts du spectacle', key: 'arts_du_spectacle' },
        { label: 'Déchèterie', key: 'decheterie' },
        { label: 'Panier (ensemble)', key: 'panier_ensemble' },
      ],
    },
    {
      key: 'colorScheme',
      label: 'Palette de couleurs',
      entries: COLOR_SCHEME_OPTIONS,
    },
  ],
  rendering: {
    titleTemplates: {
      '5min': {
        default: 'Part de la population à moins de 5min de l\'équipement ou service "{facility}"',
        police: 'Part de la population à moins de 5min d\'un commissariat de police',
        gendarmerie: 'Part de la population à moins de 5min d\'une brigade de gendarmerie',
        reseau_de_proximite_pole_emploi: 'Part de la population à moins de 5min d\'une agence Pôle emploi',
        aeroport: 'Part de la population à moins de 5min d\'un aéroport',
        gare_de_voyageurs_d_interet_nat: 'Part de la population à moins de 5min d\'une gare d\'intérêt national',
        gare_de_voyageurs_d_interet_reg: 'Part de la population à moins de 5min d\'une gare d\'intérêt régional',
        gare_de_voyageurs_d_interet_loc: 'Part de la population à moins de 5min d\'une gare d\'intérêt local',
        implantations_france_services_i: 'Part de la population à moins de 5min d\'une maison France Services',
        bureau_de_poste: 'Part de la population à moins de 5min d\'un bureau de poste',
        agence_postale: 'Part de la population à moins de 5min d\'une agence postale',
        ecole_maternelle: 'Part de la population à moins de 5min d\'une école maternelle',
        ecole_primaire: 'Part de la population à moins de 5min d\'une école primaire',
        ecole_elementaire: 'Part de la population à moins de 5min d\'une école élémentaire',
        college: 'Part de la population à moins de 5min d\'un collège',
        lycee_d_enseignement_general_et: 'Part de la population à moins de 5min d\'un lycée général et/ou technologique',
        lycee_d_enseignement_profession: 'Part de la population à moins de 5min d\'un lycée professionnel',
        lycee_d_enseignement_technique_: 'Part de la population à moins de 5min d\'un lycée agricole',
        etablissement_sante_court_sejou: 'Part de la population à moins de 5min d\'un établissement de santé (court séjour)',
        etablissement_sante_moyen_sejou: 'Part de la population à moins de 5min d\'un établissement de santé (moyen séjour)',
        etablissement_sante_long_sejour: 'Part de la population à moins de 5min d\'un établissement de santé (long séjour)',
        chirurgien_dentiste: 'Part de la population à moins de 5min d\'un chirurgien-dentiste',
        infirmier: 'Part de la population à moins de 5min d\'un·e infirmier·ère',
        laboratoire_d_analyses_et_de_bi: 'Part de la population à moins de 5min d\'un laboratoire d\'analyses médicales',
        ambulance: 'Part de la population à moins de 5min d\'un service d\'ambulance',
        pharmacie: 'Part de la population à moins de 5min d\'une pharmacie',
        cinema: 'Part de la population à moins de 5min d\'un cinéma',
        bibliotheque: 'Part de la population à moins de 5min d\'une bibliothèque',
        arts_du_spectacle: 'Part de la population à moins de 5min d\'une salle de spectacle',
        decheterie: 'Part de la population à moins de 5min d\'une déchèterie',
        panier_ensemble: 'Part de la population à moins de 5min du panier de services essentiels',
      },
      '10min': {
        default: 'Part de la population à moins de 10min de l\'équipement ou service "{facility}"',
        police: 'Part de la population à moins de 10min d\'un commissariat de police',
        gendarmerie: 'Part de la population à moins de 10min d\'une brigade de gendarmerie',
        reseau_de_proximite_pole_emploi: 'Part de la population à moins de 10min d\'une agence Pôle emploi',
        aeroport: 'Part de la population à moins de 10min d\'un aéroport',
        gare_de_voyageurs_d_interet_nat: 'Part de la population à moins de 10min d\'une gare d\'intérêt national',
        gare_de_voyageurs_d_interet_reg: 'Part de la population à moins de 10min d\'une gare d\'intérêt régional',
        gare_de_voyageurs_d_interet_loc: 'Part de la population à moins de 10min d\'une gare d\'intérêt local',
        implantations_france_services_i: 'Part de la population à moins de 10min d\'une maison France Services',
        bureau_de_poste: 'Part de la population à moins de 10min d\'un bureau de poste',
        agence_postale: 'Part de la population à moins de 10min d\'une agence postale',
        ecole_maternelle: 'Part de la population à moins de 10min d\'une école maternelle',
        ecole_primaire: 'Part de la population à moins de 10min d\'une école primaire',
        ecole_elementaire: 'Part de la population à moins de 10min d\'une école élémentaire',
        college: 'Part de la population à moins de 10min d\'un collège',
        lycee_d_enseignement_general_et: 'Part de la population à moins de 10min d\'un lycée général et/ou technologique',
        lycee_d_enseignement_profession: 'Part de la population à moins de 10min d\'un lycée professionnel',
        lycee_d_enseignement_technique_: 'Part de la population à moins de 10min d\'un lycée agricole',
        etablissement_sante_court_sejou: 'Part de la population à moins de 10min d\'un établissement de santé (court séjour)',
        etablissement_sante_moyen_sejou: 'Part de la population à moins de 10min d\'un établissement de santé (moyen séjour)',
        etablissement_sante_long_sejour: 'Part de la population à moins de 10min d\'un établissement de santé (long séjour)',
        chirurgien_dentiste: 'Part de la population à moins de 10min d\'un chirurgien-dentiste',
        infirmier: 'Part de la population à moins de 10min d\'un·e infirmier·ère',
        laboratoire_d_analyses_et_de_bi: 'Part de la population à moins de 10min d\'un laboratoire d\'analyses médicales',
        ambulance: 'Part de la population à moins de 10min d\'un service d\'ambulance',
        pharmacie: 'Part de la population à moins de 10min d\'une pharmacie',
        cinema: 'Part de la population à moins de 10min d\'un cinéma',
        bibliotheque: 'Part de la population à moins de 10min d\'une bibliothèque',
        arts_du_spectacle: 'Part de la population à moins de 10min d\'une salle de spectacle',
        decheterie: 'Part de la population à moins de 10min d\'une déchèterie',
        panier_ensemble: 'Part de la population à moins de 10min du panier de services essentiels',
      },
      '15min': {
        default: 'Part de la population à moins de 15min de l\'équipement ou service "{facility}"',
        police: 'Part de la population à moins de 15min d\'un commissariat de police',
        gendarmerie: 'Part de la population à moins de 15min d\'une brigade de gendarmerie',
        reseau_de_proximite_pole_emploi: 'Part de la population à moins de 15min d\'une agence Pôle emploi',
        aeroport: 'Part de la population à moins de 15min d\'un aéroport',
        gare_de_voyageurs_d_interet_nat: 'Part de la population à moins de 15min d\'une gare d\'intérêt national',
        gare_de_voyageurs_d_interet_reg: 'Part de la population à moins de 15min d\'une gare d\'intérêt régional',
        gare_de_voyageurs_d_interet_loc: 'Part de la population à moins de 15min d\'une gare d\'intérêt local',
        implantations_france_services_i: 'Part de la population à moins de 15min d\'une maison France Services',
        bureau_de_poste: 'Part de la population à moins de 15min d\'un bureau de poste',
        agence_postale: 'Part de la population à moins de 15min d\'une agence postale',
        ecole_maternelle: 'Part de la population à moins de 15min d\'une école maternelle',
        ecole_primaire: 'Part de la population à moins de 15min d\'une école primaire',
        ecole_elementaire: 'Part de la population à moins de 15min d\'une école élémentaire',
        college: 'Part de la population à moins de 15min d\'un collège',
        lycee_d_enseignement_general_et: 'Part de la population à moins de 15min d\'un lycée général et/ou technologique',
        lycee_d_enseignement_profession: 'Part de la population à moins de 15min d\'un lycée professionnel',
        lycee_d_enseignement_technique_: 'Part de la population à moins de 15min d\'un lycée agricole',
        etablissement_sante_court_sejou: 'Part de la population à moins de 15min d\'un établissement de santé (court séjour)',
        etablissement_sante_moyen_sejou: 'Part de la population à moins de 15min d\'un établissement de santé (moyen séjour)',
        etablissement_sante_long_sejour: 'Part de la population à moins de 15min d\'un établissement de santé (long séjour)',
        chirurgien_dentiste: 'Part de la population à moins de 15min d\'un chirurgien-dentiste',
        infirmier: 'Part de la population à moins de 15min d\'un·e infirmier·ère',
        laboratoire_d_analyses_et_de_bi: 'Part de la population à moins de 15min d\'un laboratoire d\'analyses médicales',
        ambulance: 'Part de la population à moins de 15min d\'un service d\'ambulance',
        pharmacie: 'Part de la population à moins de 15min d\'une pharmacie',
        cinema: 'Part de la population à moins de 15min d\'un cinéma',
        bibliotheque: 'Part de la population à moins de 15min d\'une bibliothèque',
        arts_du_spectacle: 'Part de la population à moins de 15min d\'une salle de spectacle',
        decheterie: 'Part de la population à moins de 15min d\'une déchèterie',
        panier_ensemble: 'Part de la population à moins de 15min du panier de services essentiels',
      },
      '20min': {
        default: 'Part de la population à moins de 20min de l\'équipement ou service "{facility}"',
        police: 'Part de la population à moins de 20min d\'un commissariat de police',
        gendarmerie: 'Part de la population à moins de 20min d\'une brigade de gendarmerie',
        reseau_de_proximite_pole_emploi: 'Part de la population à moins de 20min d\'une agence Pôle emploi',
        aeroport: 'Part de la population à moins de 20min d\'un aéroport',
        gare_de_voyageurs_d_interet_nat: 'Part de la population à moins de 20min d\'une gare d\'intérêt national',
        gare_de_voyageurs_d_interet_reg: 'Part de la population à moins de 20min d\'une gare d\'intérêt régional',
        gare_de_voyageurs_d_interet_loc: 'Part de la population à moins de 20min d\'une gare d\'intérêt local',
        implantations_france_services_i: 'Part de la population à moins de 20min d\'une maison France Services',
        bureau_de_poste: 'Part de la population à moins de 20min d\'un bureau de poste',
        agence_postale: 'Part de la population à moins de 20min d\'une agence postale',
        ecole_maternelle: 'Part de la population à moins de 20min d\'une école maternelle',
        ecole_primaire: 'Part de la population à moins de 20min d\'une école primaire',
        ecole_elementaire: 'Part de la population à moins de 20min d\'une école élémentaire',
        college: 'Part de la population à moins de 20min d\'un collège',
        lycee_d_enseignement_general_et: 'Part de la population à moins de 20min d\'un lycée général et/ou technologique',
        lycee_d_enseignement_profession: 'Part de la population à moins de 20min d\'un lycée professionnel',
        lycee_d_enseignement_technique_: 'Part de la population à moins de 20min d\'un lycée agricole',
        etablissement_sante_court_sejou: 'Part de la population à moins de 20min d\'un établissement de santé (court séjour)',
        etablissement_sante_moyen_sejou: 'Part de la population à moins de 20min d\'un établissement de santé (moyen séjour)',
        etablissement_sante_long_sejour: 'Part de la population à moins de 20min d\'un établissement de santé (long séjour)',
        chirurgien_dentiste: 'Part de la population à moins de 20min d\'un chirurgien-dentiste',
        infirmier: 'Part de la population à moins de 20min d\'un·e infirmier·ère',
        laboratoire_d_analyses_et_de_bi: 'Part de la population à moins de 20min d\'un laboratoire d\'analyses médicales',
        ambulance: 'Part de la population à moins de 20min d\'un service d\'ambulance',
        pharmacie: 'Part de la population à moins de 20min d\'une pharmacie',
        cinema: 'Part de la population à moins de 20min d\'un cinéma',
        bibliotheque: 'Part de la population à moins de 20min d\'une bibliothèque',
        arts_du_spectacle: 'Part de la population à moins de 20min d\'une salle de spectacle',
        decheterie: 'Part de la population à moins de 20min d\'une déchèterie',
        panier_ensemble: 'Part de la population à moins de 20min du panier de services essentiels',
      },
      '30min': {
        default: 'Part de la population à moins de 30min de l\'équipement ou service "{facility}"',
        police: 'Part de la population à moins de 30min d\'un commissariat de police',
        gendarmerie: 'Part de la population à moins de 30min d\'une brigade de gendarmerie',
        reseau_de_proximite_pole_emploi: 'Part de la population à moins de 30min d\'une agence Pôle emploi',
        aeroport: 'Part de la population à moins de 30min d\'un aéroport',
        gare_de_voyageurs_d_interet_nat: 'Part de la population à moins de 30min d\'une gare d\'intérêt national',
        gare_de_voyageurs_d_interet_reg: 'Part de la population à moins de 30min d\'une gare d\'intérêt régional',
        gare_de_voyageurs_d_interet_loc: 'Part de la population à moins de 30min d\'une gare d\'intérêt local',
        implantations_france_services_i: 'Part de la population à moins de 30min d\'une maison France Services',
        bureau_de_poste: 'Part de la population à moins de 30min d\'un bureau de poste',
        agence_postale: 'Part de la population à moins de 30min d\'une agence postale',
        ecole_maternelle: 'Part de la population à moins de 30min d\'une école maternelle',
        ecole_primaire: 'Part de la population à moins de 30min d\'une école primaire',
        ecole_elementaire: 'Part de la population à moins de 30min d\'une école élémentaire',
        college: 'Part de la population à moins de 30min d\'un collège',
        lycee_d_enseignement_general_et: 'Part de la population à moins de 30min d\'un lycée général et/ou technologique',
        lycee_d_enseignement_profession: 'Part de la population à moins de 30min d\'un lycée professionnel',
        lycee_d_enseignement_technique_: 'Part de la population à moins de 30min d\'un lycée agricole',
        etablissement_sante_court_sejou: 'Part de la population à moins de 30min d\'un établissement de santé (court séjour)',
        etablissement_sante_moyen_sejou: 'Part de la population à moins de 30min d\'un établissement de santé (moyen séjour)',
        etablissement_sante_long_sejour: 'Part de la population à moins de 30min d\'un établissement de santé (long séjour)',
        chirurgien_dentiste: 'Part de la population à moins de 30min d\'un chirurgien-dentiste',
        infirmier: 'Part de la population à moins de 30min d\'un·e infirmier·ère',
        laboratoire_d_analyses_et_de_bi: 'Part de la population à moins de 30min d\'un laboratoire d\'analyses médicales',
        ambulance: 'Part de la population à moins de 30min d\'un service d\'ambulance',
        pharmacie: 'Part de la population à moins de 30min d\'une pharmacie',
        cinema: 'Part de la population à moins de 30min d\'un cinéma',
        bibliotheque: 'Part de la population à moins de 30min d\'une bibliothèque',
        arts_du_spectacle: 'Part de la population à moins de 30min d\'une salle de spectacle',
        decheterie: 'Part de la population à moins de 30min d\'une déchèterie',
        panier_ensemble: 'Part de la population à moins de 30min du panier de services essentiels',
      },
      '45min': {
        default: 'Part de la population à moins de 45min de l\'équipement ou service "{facility}"',
        police: 'Part de la population à moins de 45min d\'un commissariat de police',
        gendarmerie: 'Part de la population à moins de 45min d\'une brigade de gendarmerie',
        reseau_de_proximite_pole_emploi: 'Part de la population à moins de 45min d\'une agence Pôle emploi',
        aeroport: 'Part de la population à moins de 45min d\'un aéroport',
        gare_de_voyageurs_d_interet_nat: 'Part de la population à moins de 45min d\'une gare d\'intérêt national',
        gare_de_voyageurs_d_interet_reg: 'Part de la population à moins de 45min d\'une gare d\'intérêt régional',
        gare_de_voyageurs_d_interet_loc: 'Part de la population à moins de 45min d\'une gare d\'intérêt local',
        implantations_france_services_i: 'Part de la population à moins de 45min d\'une maison France Services',
        bureau_de_poste: 'Part de la population à moins de 45min d\'un bureau de poste',
        agence_postale: 'Part de la population à moins de 45min d\'une agence postale',
        ecole_maternelle: 'Part de la population à moins de 45min d\'une école maternelle',
        ecole_primaire: 'Part de la population à moins de 45min d\'une école primaire',
        ecole_elementaire: 'Part de la population à moins de 45min d\'une école élémentaire',
        college: 'Part de la population à moins de 45min d\'un collège',
        lycee_d_enseignement_general_et: 'Part de la population à moins de 45min d\'un lycée général et/ou technologique',
        lycee_d_enseignement_profession: 'Part de la population à moins de 45min d\'un lycée professionnel',
        lycee_d_enseignement_technique_: 'Part de la population à moins de 45min d\'un lycée agricole',
        etablissement_sante_court_sejou: 'Part de la population à moins de 45min d\'un établissement de santé (court séjour)',
        etablissement_sante_moyen_sejou: 'Part de la population à moins de 45min d\'un établissement de santé (moyen séjour)',
        etablissement_sante_long_sejour: 'Part de la population à moins de 45min d\'un établissement de santé (long séjour)',
        chirurgien_dentiste: 'Part de la population à moins de 45min d\'un chirurgien-dentiste',
        infirmier: 'Part de la population à moins de 45min d\'un·e infirmier·ère',
        laboratoire_d_analyses_et_de_bi: 'Part de la population à moins de 45min d\'un laboratoire d\'analyses médicales',
        ambulance: 'Part de la population à moins de 45min d\'un service d\'ambulance',
        pharmacie: 'Part de la population à moins de 45min d\'une pharmacie',
        cinema: 'Part de la population à moins de 45min d\'un cinéma',
        bibliotheque: 'Part de la population à moins de 45min d\'une bibliothèque',
        arts_du_spectacle: 'Part de la population à moins de 45min d\'une salle de spectacle',
        decheterie: 'Part de la population à moins de 45min d\'une déchèterie',
        panier_ensemble: 'Part de la population à moins de 45min du panier de services essentiels',
      },
      '60min': {
        default: 'Part de la population à moins de 60min de l\'équipement ou service "{facility}"',
        police: 'Part de la population à moins de 60min d\'un commissariat de police',
        gendarmerie: 'Part de la population à moins de 60min d\'une brigade de gendarmerie',
        reseau_de_proximite_pole_emploi: 'Part de la population à moins de 60min d\'une agence Pôle emploi',
        aeroport: 'Part de la population à moins de 60min d\'un aéroport',
        gare_de_voyageurs_d_interet_nat: 'Part de la population à moins de 60min d\'une gare d\'intérêt national',
        gare_de_voyageurs_d_interet_reg: 'Part de la population à moins de 60min d\'une gare d\'intérêt régional',
        gare_de_voyageurs_d_interet_loc: 'Part de la population à moins de 60min d\'une gare d\'intérêt local',
        implantations_france_services_i: 'Part de la population à moins de 60min d\'une maison France Services',
        bureau_de_poste: 'Part de la population à moins de 60min d\'un bureau de poste',
        agence_postale: 'Part de la population à moins de 60min d\'une agence postale',
        ecole_maternelle: 'Part de la population à moins de 60min d\'une école maternelle',
        ecole_primaire: 'Part de la population à moins de 60min d\'une école primaire',
        ecole_elementaire: 'Part de la population à moins de 60min d\'une école élémentaire',
        college: 'Part de la population à moins de 60min d\'un collège',
        lycee_d_enseignement_general_et: 'Part de la population à moins de 60min d\'un lycée général et/ou technologique',
        lycee_d_enseignement_profession: 'Part de la population à moins de 60min d\'un lycée professionnel',
        lycee_d_enseignement_technique_: 'Part de la population à moins de 60min d\'un lycée agricole',
        etablissement_sante_court_sejou: 'Part de la population à moins de 60min d\'un établissement de santé (court séjour)',
        etablissement_sante_moyen_sejou: 'Part de la population à moins de 60min d\'un établissement de santé (moyen séjour)',
        etablissement_sante_long_sejour: 'Part de la population à moins de 60min d\'un établissement de santé (long séjour)',
        chirurgien_dentiste: 'Part de la population à moins de 60min d\'un chirurgien-dentiste',
        infirmier: 'Part de la population à moins de 60min d\'un·e infirmier·ère',
        laboratoire_d_analyses_et_de_bi: 'Part de la population à moins de 60min d\'un laboratoire d\'analyses médicales',
        ambulance: 'Part de la population à moins de 60min d\'un service d\'ambulance',
        pharmacie: 'Part de la population à moins de 60min d\'une pharmacie',
        cinema: 'Part de la population à moins de 60min d\'un cinéma',
        bibliotheque: 'Part de la population à moins de 60min d\'une bibliothèque',
        arts_du_spectacle: 'Part de la population à moins de 60min d\'une salle de spectacle',
        decheterie: 'Part de la population à moins de 60min d\'une déchèterie',
        panier_ensemble: 'Part de la population à moins de 60min du panier de services essentiels',
      },
    },
    colorSchemes: {
      '5min': { scheme: 'greens', label: '% population (5min)', percent: true },
      '10min': { scheme: 'greens', label: '% population (10min)', percent: true },
      '15min': { scheme: 'greens', label: '% population (15min)', percent: true },
      '20min': { scheme: 'greens', label: '% population (20min)', percent: true },
      '30min': { scheme: 'greens', label: '% population (30min)', percent: true },
      '45min': { scheme: 'greens', label: '% population (45min)', percent: true },
      '60min': { scheme: 'greens', label: '% population (60min)', percent: true },
    },
    dataKeys: {
      rowKey: 'dep',
      featureKey: 'INSEE_DEP',
    },
    tooltip: {
      template: 'single-metric',
    },
    valueProcessor: (row, metric) => {
      const value = row[metric]
      return value != null ? (+String(value).replace(',', '.')) / 100 : null
    },
  },
}
